name: lingo
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        cxx-version: [11, 14, 17]
        config: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: "source"
      - run: mkdir build
      - name: Configure
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DLINGO_TEST_CXX_VERSION=${{ matrix.cxx-version }} -DLINGO_WARNINGS_AS_ERRORS=ON -DLINGO_SANITIZE=ON ../source
      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.config }}
      - name: Test
        working-directory: ./build
        run: ctest --build-config ${{ matrix.config }}
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DLINGO_TEST_CXX_VERSION=17 -DLINGO_COVERAGE=ON
      - name: Build
        run: cmake --build . --config DEBUG
      - name: Test
        run: ctest --build-config Debug
      - name: Capture coverage info
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --list coverage.info
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.info
          fail_ci_if_error: true
