name: test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, ubuntu]
        os-version: [latest, 16.04, 18.04]
        cxx-version: [11, 14, 17]
        config: [Debug, Release]

        exclude:
          # os versions
          - os: windows
            os-version: 16.04
          - os: windows
            os-version: 18.04
          - os: macos
            os-version: 16.04
          - os: macos
            os-version: 18.04
          - os: ubuntu
            os-version: latest


    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: "source"
      - run: mkdir build
      - name: Configure
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DLINGO_TEST_CXX_VERSION=${{ matrix.cxx-version }} -DLINGO_WARNINGS_AS_ERRORS=ON -DLINGO_SANITIZE=ON ../source
      - name: Build
        working-directory: ./build
        run: cmake --build . --config Release
      - name: Test
        working-directory: ./build
        run: ctest
